### ISSUE TITLE
StoreFront available as apps stacks using openLiberty

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-ref-storefront/planning#13]
Target OpenShfit 4.3+
Individual repos per microservice
Web ui repo will use the nodejs-express appsody stack (Common for both spring and microprofile)
Openliberty spring repos will use the java-openliberty appsody stack - Currently supporting [Eclipse MicroProfile 3.2](https://openliberty.io/docs/ref/feature/#microProfile-3.2.html)
Each repo will be deployed using icp4apps/kabanero standard pipelines

**Comment by phemankita** [comment]
For now, halting the CP4Apps deployment. We have the instructions for local deployment [here](https://cloudnativereference.dev/deployments/appsody-mp)
