### ISSUE TITLE
Auto generate a POM file when running gradlew build for micro-customer repo

### ISSUE THREAD

**Issue by oiricaud** [ibm-garage-ref-storefront/planning#15]
The [refarch-cloudnative-micro-customer](https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-customer/tree/spring) repository does not update the `pom.xml` file.  This causes a confusion on mismatch versions. The `pom.xml` file shows `v1.5.8` for spring boot framework `build.gradle` shows `v1.3.2`

Currently the POM file is not being updated when a new build is done when using gradle. This may cause confusion to some users. 

A solution could be something along the following lines. Any thoughts?
``` xml

task createPom  {
    pom {
        project {
            groupId 'sg.test.spring.web.guide'
            artifactId 'sg-web-initial'
            version '1.0.0-SNAPSHOT'

            inceptionYear '2008'
            licenses {
                license {
                    name 'The Apache Software License, Version 2.0'
                    url 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    distribution 'repo'
                }
            }
        }
    }.writeTo("pom.xml")
```

**Comment by csantanapr** [comment]
no longer valid
