### ISSUE TITLE
Deploy Customer microservice on openshift 4.3

### ISSUE THREAD

**Issue by phemankita** [ibm-garage-ref-storefront/planning#17]
- Enable kabanero pipelines
- Use out of box java springboot pipelines
- Deploy Couchdb on openshift 4.3
- Deploy the app on openshift 4.3

**Comment by oiricaud** [comment]
Can you please provide what environment I need to deploy the customer microservice. Thank you :- )

**Comment by oiricaud** [comment]
@hollisc can you provide the url thank you :)
