### ISSUE TITLE
Appsodify Inventory microservice

### ISSUE THREAD

**Issue by phemankita** [ibm-garage-ref-storefront/planning#2]
- Use Appsody springboot stack
- Update the Inventory app to use the version of spring 2.1.12 to match the appsody stack. Currently the app is using old version of Spring 1.5.8
- Enable Swagger

Repo - https://github.com/ibm-garage-ref-storefront/inventory-ms-spring

Old Repo - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-inventory/tree/spring

**Comment by phemankita** [comment]
https://github.com/ibm-garage-ref-storefront/refarch-cloudnative-micro-inventory-spring/pull/1

Enabled appsody

**Comment by oiricaud** [comment]
I'll do the second bullet point

`Update the Inventory app to use the version of spring 2.1.12 to match the appsody stack. Currently the app is using old version of Spring 1.5.8`

**Comment by phemankita** [comment]
@oiricaud hey I worked on the catalog and inventory appsodification and finished them. Waiting on the review part. can you please pick up Auth / Customer / Orders
