### ISSUE TITLE
Mobile Application with BFF for StoreFront

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-ref-storefront/planning#21]
- [ ] Mobile Application (iOS, Android)
- [ ] Mobile BFF using the nodejs-express stack
- [ ] Deployment of MF services.  DB dependency ?? ( to be resolved )

**Comment by csantanapr** [comment]
Today we met @phemankita @csantanapr @svkrish and mobile team and discuss next steps.

A new "mobile" github repository was created to add the mobile components.

The mobile components can use for now the bluecompute devops repository to deploy the backend to make progress on their frontend work https://github.com/ibm-cloud-architecture/gse-devops/tree/master/bluecompute-ce

**Comment by svkrish** [comment]
Progress Update
-----------------
- Inclusion of template to stand up Mobile Foundation services similar to how other services are started (Complete and Merged)
- Development of ionic app for storefront with code pattern for using Mobile Foundation Auth and Storefornt App Auth in a streamlined way such that all interactions of the mobile app with the storefront is through Mobile Foundation (Completed and Merged) 
- Inclusion of code pattern to send push notifications into Orders microservice (Completed and Merged)

Work in Progress
-----------------
- Docs for setting up Mobile Foundation locally and running the mobile app 
- Docs for configuring orders microservice with Mobile Foundation endpoint and security credentials
- Inclusion of Tekton pipelines for Mobile App Registration & configuration with Mobile Foundation, building of Mobile Apps, publish of Mobile Apps.  (needs discussion to align with the other pipeline fit for storefront)

**Comment by csantanapr** [comment]
@svkrish any update on progress?

**Comment by svkrish** [comment]
@csantanapr here is the progress
- The docs for setting up and running the mobile app is complete.  Last week we had iterated on making it as simple as possible to abstract out the complexities of configuring MF server with different configuration etc. and now this is done.  Pls see https://github.com/ibm-garage-ref-storefront/storefront-mobile
- The docs for testing the orders microservice with MF will be completed by Jun 15 2020.
- The MF Tekton pipeline implementation is complete (app registration, building of client apps, publish of built apps to app center) and we will be release them for general availability soon.   How to add these pipelines into storefront is what needs to be worked out.

**Comment by csantanapr** [comment]
Thanks for the update @svkrish 

Please add the markdown docs files to the repo docs so they show up at https://cloudnativereference.dev/

For the pipelines I would add them to the devops-pipelines repo there is a stable directory maybe add a mobile sub directory and add the pipelines and tasks there.

**Comment by svkrish** [comment]
@csantanapr the doc  updates for Orders microserivce integrating with MF is completed.  

Also content for Storefront Mobile App has been updated to the appropriate pages in https://cloudnativereference.dev/

**Comment by csantanapr** [comment]
This is great @svkrish 👍 
Looking forward to trying MF myself 
Thank you the team for the contributions 🎉
