### ISSUE TITLE
Add content about Resiliency 

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-ref-storefront/planning#28]
There two papers that talk about the Resilience of th StoreFront App

- We should incorporate feedback from team into the new version
- We should include the documentation on Resiliency in the docs website
    - https://www.ibm.com/cloud/architecture/files/HADR-for-apps-based-on-containers.pdf
    - https://www.ibm.com/cloud/architecture/files/HADR-for-applications-based-on-containers-part-2.pdf

**Comment by oiricaud** [comment]
Did you write those PDF files? Bravo love it!
