### ISSUE TITLE
Add unit testing to java microservices

### ISSUE THREAD

**Issue by phemankita** [ibm-garage-ref-storefront/planning#31]
Implement unit testing to all the services

- [x] [Inventory](https://github.com/ibm-garage-ref-storefront/inventory-ms-spring)
- [x] [Catalog](https://github.com/ibm-garage-ref-storefront/catalog-ms-spring)
- [x] [Customer](https://github.com/ibm-garage-ref-storefront/customer-ms-spring)
- [x] [Auth](https://github.com/ibm-garage-ref-storefront/auth-ms-spring)
- [x] [Orders](https://github.com/ibm-garage-ref-storefront/orders-ms-spring)

**Comment by oiricaud** [comment]
Created a [pull request-6](https://github.com/ibm-garage-ref-storefront/inventory-ms-spring/pull/6) for [Inventory microservice ](https://github.com/ibm-garage-ref-storefront/inventory-ms-spring) to include a plain [smoke test and actuator test](https://www.quora.com/What-is-smoke-testing-and-why-is-it-necessary).

**Comment by oiricaud** [comment]
Created a [pull request-4](https://github.com/ibm-garage-ref-storefront/auth-ms-spring/pull/4) for [Auth microservice](https://github.com/ibm-garage-ref-storefront/auth-ms-spring) microservice to include a plain smoke test and actuator test.

**Comment by oiricaud** [comment]
Created a [pull request-4](https://github.com/ibm-garage-ref-storefront/orders-ms-spring/pull/4)  for the  [Orders](https://github.com/ibm-garage-ref-storefront/orders-ms-spring) microservice to include a plain smoke test and actuator test.

**Comment by oiricaud** [comment]
Created a [pull request-4](https://github.com/ibm-garage-ref-storefront/catalog-ms-spring/pull/4) for the [Catalog microservice](https://github.com/ibm-garage-ref-storefront/catalog-ms-spring) to include a plain smoke test and actuator test.

**Comment by oiricaud** [comment]
FYI
I believe I found a bug on appsody view more details [appsody-issue-821](https://github.com/appsody/stacks/issues/821). In summary when using a `appsody init` on your spring boot stack, the `MainTests class` does not run the unit tests. Refactoring the default name of the class resolves this issue.

**Comment by oiricaud** [comment]
Created a [pull request-13](https://github.com/ibm-garage-ref-storefront/customer-ms-spring/pull/13) for the [Customer microservice](https://github.com/ibm-garage-ref-storefront/customer-ms-spring) to include a plain smoke test and actuator test.

**Comment by oiricaud** [comment]
@phemankita Can you review this when you get a chance, thanx

**Comment by oiricaud** [comment]
Resolve ActuatorTests for all microservices:

**Comment by phemankita** [comment]
@oiricaud We shd have simple tests for this to validate the app flow. For this the tests should be independent of the databases.

Necessary methods can be mocked using Mockito
