### ISSUE TITLE
Document Deploy storefront to openshift 

### ISSUE THREAD

**Issue by phemankita** [ibm-garage-ref-storefront/planning#34]
- Deploy all the microservices to openshift 4.3 
- Then define necessary script to run the steps

Like have one master deploy script `./deploy-storefront <module>` and then you can have individual scripts like `./deploy-storefront git` to clone the repos,  `./deploy-storefront db` to deploy db and then  `./deploy-storefront app` to deploy the microservices

Reference - https://cp4apps.cloudnative101.dev/web/1.0.0/appsody-deploy.html 

Document the process here - https://cloudnativereference.dev/deployments/openshift

**Comment by csantanapr** [comment]
From today's meeting

- Create namespace
- Deploy databases
- Configure the databases
- Create a github org
- Fork the spring repo and other to the org
- Deploy using cp4apps/kabanero pipelines
- Access the app via OpenShift Route

Reference to script the repo creation could use the github beta CLI https://cli.github.com/

**Comment by phemankita** [comment]
- [x] Dev namespace name will be `storefront-dev` (For this update all repo's appsody deploy to change the namespace to storefront-dev)
- [x] Create a github org 
- [x] Write a script to fork all the `spring` related repositories to the created org and clone them.
- [x] Database automation script - #33 
- [ ] Set up webhook triggers using UI
- [ ] Document steps to deploy all microservices
- [ ] Create pipeline called `deploy-storefront-ms-to-openshift-pl`

@oiricaud @hkang92

**Comment by phemankita** [comment]
PRs for namespace change

- https://github.com/ibm-garage-ref-storefront/inventory-ms-spring/pull/8 
- https://github.com/ibm-garage-ref-storefront/catalog-ms-spring/pull/5
- https://github.com/ibm-garage-ref-storefront/customer-ms-spring/pull/14
- https://github.com/ibm-garage-ref-storefront/auth-ms-spring/pull/5
- https://github.com/ibm-garage-ref-storefront/orders-ms-spring/pull/5
- https://github.com/ibm-garage-ref-storefront/storefront-ui/pull/10

**Comment by oiricaud** [comment]
What should i call the github org? @phemankita

**Comment by oiricaud** [comment]
Created github org https://github.com/storefront-dev

**Comment by oiricaud** [comment]
To run the following script `initials=enter-your-initials ./run.sh`
```bash
export org=storefront-dev
spring_repos=([1]="orders-ms-spring" [2]="auth-ms-spring" [3]="customer-ms-spring" [4]="catalog-ms-spring" [5]="inventory-ms-spring")

cd ..

# create empty repo
for repo in "${spring_repos[@]}"
do 
    echo "Creating repo $repo " 
    echo -e "n" | gh repo create $org/$repo --public
    
done

sleep 5

# clone repo
for repo in "${spring_repos[@]}"
do 
    echo "Creating repo $repo " 
    gh repo clone https://github.com/ibm-garage-ref-storefront/$repo
    
done

sleep 5

# Push all new repos to the org
for repo in "${spring_repos[@]}"
do 
    echo "Pushing repo $repo "
    pwd
    echo "cding to the repo"
    cd $repo
    pwd
    git init
    git add .
    git remote add origin https://github.com/$org/$repo
    git commit -m "forked $repo from storefront"
    git push -u origin master
    # cd ..
    echo "cding up"
    cd ../
    pwd
done

```

**Comment by phemankita** [comment]
Database automation

https://github.com/ibm-garage-ref-storefront/storefront-databases

**Comment by oiricaud** [comment]
Repository automator

https://github.com/ibm-garage-ref-storefront/storefront-repo-automator/blob/master/run.sh

**Comment by hkang92** [comment]
@csantanapr @phemankita  Oscar and I are working on the last part which is (Set up webhook triggers using UI) but we are not sure which cluster we are suppose to use on the IBM CPAT account. Can you confirm which one we can use if it is on the list?

<img width="1817" alt="Screen Shot 2020-06-05 at 3 05 21 PM" src="https://user-images.githubusercontent.com/38839544/83918309-14fa9980-a73e-11ea-9e5f-08d77ded11a2.png">

**Comment by phemankita** [comment]
We need CP4Apps installed on them. Do you have access to the cluster in CASE account or DevOps env ?

**Comment by oiricaud** [comment]
She doesn’t if I remember correctly

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by oiricaud** [comment]
Wanted to share a status update. I created a new pipeline named `deploy-storefront-ms-to-openshift-pl` and integrated the automator-git script I wrote last week, but unfortonetly I am hitting a blocker. I am trying to authorize the GH Cli on the tekton container but I get the following:

```bash
Github Organization:  storefront-dev
Github Initials:  ea
Creating repo  dev: storefront-dev/orders-ms-spring-ea
Notice: authentication required
Press Enter to open github.com in your browser... error opening web browser: exec: "xdg-open": executable file not found in $PATH
Please open the following URL manually:
https://github.com/login/oauth/authorize?client_id=178c6fc778ccc68e1d6a&redirect_uri=http%3A%2F%2F127.0.0.1%3A38718%2Fcallback&scope=repo+read%3Aorg+gist&state=7ef0f3cc526c3e9f6030
If you are on a server or other headless system, use this workaround instead:  1. Complete authentication on a GUI system  2. Copy the contents of ~/.config/gh/config.yml to this syste
```

**Comment by hkang92** [comment]
Status update: We added the following table of contents, pre-reqs, create an organization, create and trigger webhook. 

We just need to add more information with the images attached and we are good to go. 

https://github.com/ibm-garage-ref-storefront/docs/pull/2

FYI: still a working progress

**Comment by oiricaud** [comment]
Prior to having a discussion with Hema, I recently learned that the feature [request](https://github.com/cli/cli/issues/1154#event-3433656920) I made for the `GH Cli` will be coming in the next release. This feature request is necessary if we decide to move forward on creating a pipeline such as `deploy-storefront-ms-to-openshift-pl` to generate all ms-repos onto the users' organization. Then we can add another task to this pipeline to deploy these ms-repos onto openshift. But for now as Hema mentioned, is a nice to have but not required for this ticket.

**Comment by oiricaud** [comment]
Can you review our [pull request](https://github.com/ibm-garage-ref-storefront/docs/pull/2)?

**Comment by phemankita** [comment]
I only see the index ... I don't see any content there. Did you push the changes ?

**Comment by oiricaud** [comment]
https://github.com/hkang92/docs/blob/storefront-tutorial/src/pages/deployments/openshift.mdx looks like we created the pull request for the wrong branch

**Comment by oiricaud** [comment]
Here is the new pull request, sorry about that https://github.com/ibm-garage-ref-storefront/docs/pull/3
