### ISSUE TITLE
QA: Why the initials get appended to every repository in automator?

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-ref-storefront/planning#39]
I have the following question from the docs here
https://cloudnativereference.dev/deployments/openshift

Why the initials get appended to every repository in automator?

![image](https://user-images.githubusercontent.com/1094878/84834267-fda19300-affe-11ea-9b0e-370816ebdf3e.png)

cc @oiricaud

**Comment by oiricaud** [comment]
Good question! Thanks for asking. I thought the requirements was to create an organization in which all users can share this org. I added the initials to differentiate between users’ repo. I can change this if you’d like!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by csantanapr** [comment]
🧐 
I think it might be a good idea to have an option for the initials. 

How about by default there is no initials added. 

User can optimally specified initials via env variable but I would not add them at the end as suffix make it a prefix at the beginning of every repo this its easier to sort and find repos for user “hk-“

What do you think @oiricaud ?

**Comment by oiricaud** [comment]
No problem, will add this to my backlog and work on this tomorrow morning. Thanks for the feedback :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by oiricaud** [comment]
Add two edge cases: 

- [x] 1) If user is the only person using the newly created organization
- [x] 2) If user is sharing the organization among other users.

1) Resolved:
<img width="1914" alt="Screen Shot 2020-06-18 at 3 03 51 PM" src="https://user-images.githubusercontent.com/11867058/85066613-ee445600-b174-11ea-80e7-020e879f4a6e.png">

2) Resolved:
<img width="961" alt="Screen Shot 2020-06-18 at 3 16 50 PM" src="https://user-images.githubusercontent.com/11867058/85067720-bf2ee400-b176-11ea-96f5-6d332726a382.png">

You can view the changes [storefront-automator](https://github.com/ibm-garage-ref-storefront/storefront-repo-automator)
