### ISSUE TITLE
Add to the site docs for how to work with customized pipelines and automate their release

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-ref-storefront/planning#44]
On this section 
https://cloudnativereference.dev/related-repositories/pipelines

Answer the following questions:
- How can the user use our custom pipelines to get started?
- Allow the user to introspect and really understand how these decoupled kabanero tasks can be reused with our custom pipelines.

**Comment by oiricaud** [comment]
Created pull request https://github.com/ibm-garage-ref-storefront/docs/pull/6

**Comment by phemankita** [comment]
Made few additions - https://github.com/ibm-garage-ref-storefront/docs/pull/7

**Comment by oiricaud** [comment]
**Feedback Carlos Gave**

Currently this section https://cloudnativereference.dev/related-repositories/pipelines 
Is not showing users how to add the custom pipelines but rather explaining to the user how to use the git-package-pipeline manager. I will resolve this as soon as possible.
