### ISSUE TITLE
Appsodify inventory microservice

### ISSUE THREAD

**Issue by phemankita** [ibm-garage-ref-storefront/planning#47]
- Use Appsody `java-openliberty` stack
- Update the Inventory app to use the microprofile version that matches the current appsody stack. 

Repo - https://github.com/ibm-garage-ref-storefront/inventory-ms-openliberty

Old Repo - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-inventory/tree/microprofile

Note: Make sure the api rest endpoints are same as the ones we using the spring version so that the web app will be functional for both of them. If they are different in the older version, change them to match the current spring version.

Endpoint - `/micro/inventory`

**Comment by oiricaud** [comment]
Made a pull request https://github.com/ibm-garage-ref-storefront/inventory-ms-openliberty/pull/5

**Comment by phemankita** [comment]
Just left with Opentracing ... @phemankita will fill this in along with Catalog
