### ISSUE TITLE
Appsodify Customer Microservice

### ISSUE THREAD

**Issue by phemankita** [ibm-garage-ref-storefront/planning#5]
- Use Appsody springboot stack
- Update the Customer app to use the version of spring 2.1.12 to match the appsody stack. Currently the app is using old version of Spring 1.5.8
- Enable swagger

Old Repo - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-customer/tree/spring

New Repo - https://github.com/ibm-garage-ref-storefront/customer-ms-spring

**Comment by oiricaud** [comment]
I used the https://start.spring.io/ to generate the gradle file with the dependencies. I used spring boot 2.2.6. Do you think we can update the stack to use 2.2.6?

**Comment by phemankita** [comment]
We wanted to initialize it as an appsody template like `appsody init kabanero/stack` and then define the code on top of it.

**Comment by oiricaud** [comment]
Okay great! It seems like the cloudant version is refusing to connect to the localhost. Not sure if this is an issue with the newer version of security and cloudant. Can you move this ticket to `Progress`? 

<img width="1420" alt="Screen Shot 2020-05-04 at 7 46 38 AM" src="https://user-images.githubusercontent.com/11867058/80967078-64664680-8ddb-11ea-8abd-5fc43b009657.png">

**Comment by oiricaud** [comment]
https://github.com/oiricaud/customer-ms-spring i'll create a pull request very soon

**Comment by oiricaud** [comment]
Created a [pull request](https://github.com/ibm-garage-ref-storefront/customer-ms-spring/pull/1)  @phemankita can you test this to see if it runs in your local machine? You should just need to run `appsody run`
