### ISSUE TITLE
Customer details are not showing on the UI

### ISSUE THREAD

**Issue by oiricaud** [ibm-garage-ref-storefront/planning#58]
The `storefront-ui` microservice is not showing all of the customer details.

Run this locally and debug why the customer details are not showing in the `storefront-ui` microservice.

Tasks:
Run these microservices locally to reproduce the issue that we are having in production.
- [x] [customer-ms-spring](https://github.com/ibm-garage-ref-storefront/customer-ms-spring)
- [x] [auth-ms-spring](https://github.com/ibm-garage-ref-storefront/auth-ms-spring)
- [x] [storefront-ui](https://github.com/ibm-garage-ref-storefront/storefront-ui)

Once you are able to reproduce the issue locally of the user unable to view the customer details in the `storefront-ui`; you can begin to debug `storefront-ui` microservice. 

My best guess the data from the `customer-ms-spring` is not giving the correct 200 response OR the `storefront-ui` is calling the incorrect rest endpoint. 

**Reminder**
You should be using `appsody run` to run any of the microservices.

**Comment by oiricaud** [comment]
@hkang92 If you want to pair program to tackle this task, let me know :)

**Comment by oiricaud** [comment]
Pull requests have been made 
- https://github.com/ibm-garage-ref-storefront/auth-ms-spring/pull/8
- https://github.com/ibm-garage-ref-storefront/customer-ms-spring/pull/19
- https://github.com/ibm-garage-ref-storefront/storefront-ui/pull/19

**Comment by phemankita** [comment]
PRs merged
