### ISSUE TITLE
harcoded gitops repo in gitops task

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-ref-storefront/planning#60]
https://github.com/ibm-garage-ref-storefront/devops-pipelines/blob/master/pipelines/stable/storefront-springboot/tasks/gitops.yaml#L47

**Comment by phemankita** [comment]
https://github.com/ibm-garage-ref-storefront/devops-pipelines/pull/22 closes this

**Comment by phemankita** [comment]
https://github.com/ibm-garage-ref-storefront/devops-pipelines/pull/23 fixes nodejs pipeline too
