### ISSUE TITLE
Error while using sonar scan with IBM Garage DevOps pipeline customization

### ISSUE THREAD

**Issue by indirakalagara** [ibm-garage-ref-storefront/planning#70]
Below is the error while trying out the Sonar Scan using the  devops-pipeline repository from the IBM garage github. This is forked to customize. 

Starting sonar scan
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/dev/appsody/java-spring-boot-mvc-data-liberty/maven-metadata.xml
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM dev.appsody:java-spring-boot-mvc-data-liberty:[0.1, 0.2) for dev.appsody.starter.java-spring-boot-mvc-data-liberty:account-app:1.0-SNAPSHOT: No versions matched the requested parent version range '[0.1, 0.2)' and 'parent.relativePath' points at no local POM @ line 6, column 13
@
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR] The project dev.appsody.starter.java-spring-boot-mvc-data-liberty:account-app:1.0-SNAPSHOT (/workspace/git-source/sonarscan/user-app/pom.xml) has 1 error
[ERROR] Non-resolvable parent POM dev.appsody:java-spring-boot-mvc-data-liberty:[0.1, 0.2) for dev.appsody.starter.java-spring-boot-mvc-data-liberty:account-app:1.0-SNAPSHOT: No versions matched the requested parent version range '[0.1, 0.2)' and 'parent.relativePath' points at no local POM @ line 6, column 13 -> [Help 2]

To correct this error , have used the following workaround
   - add appsody extract as a step in the sonar scan task 
   - and then used the scan task folder to run mvn sonar command  
-    and provide relative path in the  appsody project pom.xml like this <relativePath>../pom.xml</relativePath>

This is just a workaround, request you to let us know how to resolve the above.

**Comment by oiricaud** [comment]
Greetings,

Thank you for taking the time to submit this issue. It seems like the issue is related with the Appsody stacks you are using. I would verify the version of appsody you are using and use a later version to see if this issue gets resolved. I want to remind you that Appsody only supports Spring Boot 2.x, so if you are using a later version of spring version, appsody may not work as intended. 

You can update your microservice to spring boot 2.x.

**Comment by phemankita** [comment]
CP4A not valid anymore
