### ISSUE TITLE
Enable Jaegar using opentracing in mp version using openliberty stack

### ISSUE THREAD

**Issue by phemankita** [ibm-garage-ref-storefront/planning#71]
Figure out how to integrate jaeger with openliberty mp services

**Comment by csantanapr** [comment]
Here is a lab using jaeger and microprofile on openliberty

**Comment by phemankita** [comment]
https://github.com/ibm-garage-ref-storefront/inventory-ms-openliberty/pull/8/
https://github.com/ibm-garage-ref-storefront/catalog-ms-openliberty/pull/2

We can follow the same to enable it in the rest of the microsevices too
