### ISSUE TITLE
CORS issue.

### ISSUE THREAD

**Issue by kitty-catt** [ibm-garage-ref-storefront/planning#77]
When I deploy Blue Compute on Code Ready Containers, then it gives CORS exceptions upon login and displaying the profile. 

We can login, make orders, and see the order history.

We cannot see the customer details ... and we see the CORS exception when debugging via the browser.

We tried allowing CORS via plugins in firefox as well a chrome - this workaround does not work.

I will redeploy BC and provide further details.

**Comment by phemankita** [comment]
Attaching screenshot from last call 

<img width="1440" alt="Screen Shot 2021-01-21 at 2 17 59 PM" src="https://user-images.githubusercontent.com/19691920/105979356-99c56980-60b9-11eb-94d4-04e7588a1e5d.png">
